services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    platform: "linux/amd64"
    restart: unless-stopped
    command: ["python3", "run.py"]
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      MYSQL_CONN: ${MYSQL_CONN}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bot
      MYSQL_USER: bot
      MYSQL_PASSWORD: ${MYSQL_BOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql/
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
